export const links = {
  login: 'login',
  cadastrar: 'cadastrar',
  profissional: 'profissional',
  contratar: 'contratar',
  buscar: 'buscar',
  sobre: 'sobre-nos',
  comoFunciona: 'como-funciona',
  trabalheConosco: 'trabalhe-conosco',
  paraEmpresas: 'para-empresas',
  planos: 'planos',
  contratos: 'contratos',
  solicitacoes: 'solicitacoes',
  faq: 'pergunta-frequente',
  politicaPrivacidade: 'politica-de-privacidade',
  verificar: 'verificar-profissional',
  termosUso: 'termos-de-uso',
  recuperarSenha: 'recuperar-senha',
} as const
